DROP DATABASE IF EXISTS GILDEDROSE; 
CREATE DATABASE IF NOT EXISTS GILDEDROSE; 
use gildedrose;

/* TABALA ITEMS*/

DROP TABLE IF EXISTS ITEMS;
CREATE TABLE IF NOT EXISTS ITEMS
(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	NAME_ITEM VARCHAR(50) NOT NULL,
    SELLIN INT NOT NULL,
    QUALITY INT NOT NULL,
    /********************************/
    PRIMARY KEY(ID)
)ENGINE INNODB;

DROP TABLE IF EXISTS NORMALITEMS;
CREATE TABLE IF NOT EXISTS NORMALITEMS
(
	ITEM INT UNSIGNED NOT NULL,
    /**************************/
    PRIMARY KEY(ITEM),
    FOREIGN KEY (ITEM) REFERENCES ITEMS(ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
)ENGINE INNODB;

DROP TABLE IF EXISTS SULFURAS;
CREATE TABLE IF NOT EXISTS SULFURAS
(
	ITEM INT UNSIGNED NOT NULL,
    /**************************/
    PRIMARY KEY(ITEM),
    FOREIGN KEY (ITEM) REFERENCES ITEMS(ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
)ENGINE INNODB;

DROP TABLE IF EXISTS CONJURED;
CREATE TABLE IF NOT EXISTS CONJURED
(
	ITEM INT UNSIGNED NOT NULL,
    /**************************/
    PRIMARY KEY(ITEM),
    FOREIGN KEY (ITEM) REFERENCES ITEMS(ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
)ENGINE INNODB;

DROP TABLE IF EXISTS AGEDBRIE;
CREATE TABLE IF NOT EXISTS AGEDBRIE
(
	ITEM INT UNSIGNED NOT NULL,
    /**************************/
    PRIMARY KEY(ITEM),
    FOREIGN KEY (ITEM) REFERENCES ITEMS(ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
)ENGINE INNODB;

DROP TABLE IF EXISTS BACKSTAGEPASS;
CREATE TABLE IF NOT EXISTS BACKSTAGEPASS
(
	ITEM INT UNSIGNED NOT NULL,
    /**************************/
    PRIMARY KEY(ITEM),
    FOREIGN KEY (ITEM) REFERENCES ITEMS(ID)
		ON DELETE CASCADE
        ON UPDATE CASCADE
)ENGINE INNODB;

INSERT INTO ITEMS
(NAME_ITEM, QUALITY, SELLIN)
VALUES
("+5 Dexterity Vest", 10, 20),
("Aged Brie", 2, 0),
("Elixir of the Mongoose", 5, 7),
("Sulfuras, Hand of Ragnaros", 80, 0),
("Sulfuras, Hand of Ragnaros", 80, -1),
("Backstage passes to a TAFKAL80ETC concert", 20, 15),
("Backstage passes to a TAFKAL80ETC concert", 49, 10),
("Backstage passes to a TAFKAL80ETC concert", 49, 6),
("Conjured Mana Cake", 3, 6);

INSERT INTO AGEDBRIE
(ITEM)
VALUES
(2);

INSERT INTO backstagepass
(ITEM)
VALUES
(6),(7),(8);

INSERT INTO conjured
(ITEM)
VALUES
(9);

INSERT INTO normalitems
(ITEM)
VALUES
(1),(3);

INSERT INTO sulfuras
(ITEM)
VALUES
(4),(5);
